# Site
name: "The Beacon"
description: "The Beacon is Martingrove's newspaper."
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: ""
email: "fake@gmail.com"
instagram: "https://instagram.com/mcibeacon"
management_site: "https://admin.mcibeacon.ml"

include: ["_pages"]
permalink: /:year/:month/:title.html

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-seo-tag

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: unknown

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
pagination:
  enabled: true
  per_page: 10
  permalink: "/page/:num/"

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
  ]

keep_files: [CNAME,.git,]

authors:
  unknown:
    name: Unknown
    avatar: assets/images/avatar1.jpg
    bio: "If you see this, something went wrong, and this page has no author set up for it."
    email: mcibeacon@gmail.com
    instagram: https://instagram.com/mcibeacon

  srao:
    name: "Surbhi Rao"
    #avatar: assets/images/surbhi-rao.jpg
    bio: "Hi, I'm Surbhi, the editor-in-chief of The Beacon. I hope you like it!"
    instagram: https://instagram.com/mcibeacon

  tharlow:
    name: "Tashema Harlow"
    bio: "I'm Tashema, editor-in-chief of The Beacon with Surbhi."
    instagram: https://instagram.com/mcibeacon

  ewong:
    name: "Emma Wong"
    bio: "Copy Editor."
    instagram: https://instagram.com/mcibeacon

  anaing:
    name: "April Naing"
    bio: "Copy Editor."
    instagram: https://instagram.com/mcibeacon

  cmac:
    name: "Cole Anthony Capilongo"
    bio: "ğ“£ğ“±ğ“® ğ“¦ğ“®ğ“«ğ“¶ğ“ªğ“¼ğ“½ğ“®ğ“»"
    instagram: https://instagram.com/mcibeacon

  jvilladarez:
    name: "Jeremy Ricci Villadarez"
    bio: "Photography Head."
    instagram: https://instagram.com/mcibeacon

  ssagar:
    name: "Swamini Sagar"
    bio: "Assistant Photography Head."
    instagram: https://instagram.com/mcibeacon

  pdhugga:
    name: "Parneet Dhugga"
    bio: "Comic and Illustration Head."
    instagram: https://instagram.com/mcibeacon

  mmohammed:
    name: "Muna Mohammed"
    bio: "Publicity Head."
    instagram: https://instagram.com/mcibeacon

  rmatharu:
    name: "Rhea Matharu"
    bio: "Copy Editor."
    instagram: https://instagram.com/mcibeacon

  tpatel:
    name: "Tvisha Patel"
    bio: "Secretary."
    instagram: https://instagram.com/mcibeacon

  smahmud:
    name: "Sanaa Mahmud"
    bio: "Columnist."
    instagram: https://instagram.com/mcibeacon

  hnur:
    name: "Huda Nur"
    bio: "Columnist."
    instagram: https://instagram.com/mcibeacon


  ntelesford:
    name: "Naomi Telesford"
    bio: "Contributor."
    instagram: https://instagram.com/mcibeacon


  mhutzul:
    name: "Maya Hutzul"
    bio: "Columnist."
    instagram: https://instagram.com/mcibeacon

  lli:
    name: "Linda Li"
    bio: "Columnist."
    instagram: https://instagram.com/mcibeacon

  epark:
    name: "Emily Park"
    bio: "General Council member."
    instagram: https://instagram.com/mcibeacon

  lbalakrishnan:
    name: "Lavini Balakrishnan"
    bio: "General Council member."
    instagram: https://instagram.com/mcibeacon

  aansah:
    name: "Ama Ansah"
    bio: "General Council member."
    instagram: https://instagram.com/mcibeacon

  eliang:
    name: "Ethan Liang"
    bio: "General Council member."
    instagram: https://instagram.com/mcibeacon

  mdominguez-schatz:
    name: "Micah Dominguez-Schatz"
    bio: "Contributor."
    instagram: https://instagram.com/mcibeacon

  ifuse-katayama:
    name: "Ira Fuse-Katayama"
    bio: "Contributor."
    instagram: https://instagram.com/mcibeacon

  sgehlaut:
    name: "Sara Gehlaut"
    bio: "Contributor."
    instagram: https://instagram.com/mcibeacon

  nyotis:
    name: "Nicole Yotis"
    bio: "Columnist."
    instagram: https://instagram.com/mcibeacon

  cmiszkiel:
    name: "Caroline Miszkiel"
    bio: "Contributor."
    instagram: https://instagram.com/mcibeacon

  amehta:
    name: "Ambika Mehta"
    bio: "Contributor."
    instagram: https://instagram.com/mcibeacon

  ezhang:
    name: "Elena Zhang"
    bio: "Contributor."
    instagram: https://instagram.com/mcibeacon

  rsyed:
    name: "Rida Syed"
    bio: "Comics and Illustrations."
    instagram: https://instagram.com/mcibeacon

  ekim:
    name: "Emily Kim"
    bio: "Copy Editor."
    instagram: https://instagram.com/mcibeacon


  lbaumgart:
    name: "Luke Baumgart"
    bio: "Contributor."
    instagram: https://instagram.com/mcibeacon

  aaden-sabriye:
    name: "Aaliyah Aden-Sabriye"
    bio: "Contributor."
    instagram: https://instagram.com/mcibeacon

  sliao:
    name: "Susanna Liao"
    bio: "Contributor."
    instagram: https://instagram.com/mcibeacon

  dbrebeanu:
    name: "Diana Brebeanu"
    bio: "Contributor."
    instagram: https://instagram.com/mcibeacon
